### ISSUE TITLE
IO one by one anki qt5

### ISSUE THREAD

**Issue by cwmschmidty** [hgiesel/closet#107]
**Describe the bug**
Hi,

Have tried editing an existing card to IO one by one and also creating new one. I receive this error when I hit add new card. When I close the error I can add the card but there is no IO on the card in preview or if I set the card to due. Also, the IO one by one example card also doesn't work. I also noticed I can't add any new cards now without receiving the same error.

**Debug information**

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-08-20 02:20:17

Caught exception:
Traceback (most recent call last):
File "aqt.webview", line 568, in handler
File "aqt.editor", line 561, in
File "aqt.addcards", line 259, in _add_current_note
File "aqt.addcards", line 294, in _note_can_be_added
File "aqt.hooks_gen", line 172, in call
File "C:\Users\J\AppData\Roaming\Anki2\addons21\272311064\src\addcards.py", line 18, in check_if_occlusion_editor_open
if addcards.editor.occlusion_editor_active
AttributeError: 'NoneType' object has no attribute 'editor'

#### Method 1 (preferred method)

1. You put the cards which do not work (however many you like), and put them into a new Anki Deck.
1. You export it by finding it on the main screen, clicking on the small right cog (wheel) next to it, and choose "Export"
1. As Export format choose "**Anki Deck Package**", **uncheck** "Include scheduling information", **check** "Include media".
1. You will get a file with the ending ".apkg". Upload this file here.

**Comment by cwmschmidty** [comment]
[Default.zip](https://github.com/hgiesel/closet/files/9387352/Default.zip)
![1 - allowing me to cloze](https://user-images.githubusercontent.com/58187956/185752712-1cbaedfc-d53b-4194-8059-9dc6439e96f9.png)
![2 - accept](https://user-images.githubusercontent.com/58187956/185752714-66c7d655-df7f-491f-a9c4-1181e6646770.png)
![3 - inputted IO field](https://user-images.githubusercontent.com/58187956/185752715-abad0ad7-8042-4ac9-b247-024a862da708.png)
![4 - error](https://user-images.githubusercontent.com/58187956/185752716-b8bba6ff-b493-4199-85ea-752346aa8d73.png)
![5 - hit add again and card adds](https://user-images.githubusercontent.com/58187956/185752718-79e4c238-2c63-4ece-8e96-2d6b74ae8749.png)
![6 - backside of card has no clozes](https://user-images.githubusercontent.com/58187956/185752719-562c3bea-96b2-488a-ab51-0ba0b6abf813.png)
)
