### ISSUE TITLE
Issues with adding new cards

### ISSUE THREAD

**Issue by cwmschmidty** [hgiesel/closet#108]
**Describe the bug**

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-08-28 13:38:49

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "aqt.webview", line 149, in _onCmd
  File "aqt.webview", line 618, in _onBridgeCmd
  File "aqt.hooks_gen", line 4358, in __call__
  File "C:\Users\J\AppData\Roaming\Anki2\addons21\272311064\src\webview\__init__.py", line 90, in add_occlusion_messages
    on_cloze(editor)
  File "C:\Users\J\AppData\Roaming\Anki2\addons21\272311064\src\editor\__init__.py", line 182, in on_cloze
    return _old(editor)
NameError: name '_old' is not defined

Error appears everytime I add a new card. After closing the error the card will add normally.

**Comment by otmanebns** [comment]
Hello cwmschmidty), I saw you were a medicine student too. I'm trying to use closet but I can't use it and there's no tutorial / video or website explaining how to do. May you message me on twitter (@otmanebns) or on discord (sieg#0001) because I really need to understand how it works. Thank you !

**Comment by Andysk13** [comment]
I have the same bug, I've been unable to find a solution
