### ISSUE TITLE
Error appears when creating default anki cloze deletion

### ISSUE THREAD

**Issue by justarmadillo** [hgiesel/closet#115]
**Describe the bug**
When doing cloze card type (default anki cloze card type) and press **CTRL+SHIFT+C** to make cloze deletion the error message appears

- Anki client: Anki windows 2.1.57

**Debug information**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.57 (6b7d372c) Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-30 21:47:32

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 43, in cmd
  File "aqt.webview", line 150, in _onCmd
  File "aqt.webview", line 614, in _onBridgeCmd
  File "_aqt.hooks", line 5002, in __call__
  File "C:\Users\Oracle\AppData\Roaming\Anki2\addons21\272311064\src\webview\__init__.py", line 90, in add_occlusion_messages
    on_cloze(editor)
  File "C:\Users\Oracle\AppData\Roaming\Anki2\addons21\272311064\src\editor\__init__.py", line 182, in on_cloze
    return _old(editor)
NameError: name '_old' is not defined

**Comment by justarmadillo** [comment]
anyone who still have the same problem, I've fixed the errors manually (Anki 23.10.1 Qt6)
you can install the addon manually via this file:
https://mega.nz/file/t00hSDwY#WCJjIYpkdK0fyOMEoZ4Z8WuLhywgXmG0NaeJUXAjaWs

**Comment by QuietBasil** [comment]
I am getting the following error too whenever I create a random new cloze deletion anywhere on anki.
But I get it only once after starting anki and then it doesn't show up on the next clozes I make. 
There is no functional issue using anki but just that it is a little annoying so I just ignore it hoping the developers will fix it in the next update.
Really appreciate your work developers, thank you!


Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.19045
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-12-22 07:56:39
Add-ons possibly involved: ⁨Closet For Anki⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 50, in cmd
  File "aqt.webview", line 157, in _onCmd
  File "aqt.webview", line 680, in _onBridgeCmd
  File "_aqt.hooks", line 5415, in __call__
  File "C:\Users\shrut\AppData\Roaming\Anki2\addons21\272311064\src\webview\__init__.py", line 90, in add_occlusion_messages
    on_cloze(editor)
  File "C:\Users\shrut\AppData\Roaming\Anki2\addons21\272311064\src\editor\__init__.py", line 182, in on_cloze
    return _old(editor)
NameError: name '_old' is not defined
